name = "rails8"

[build]
onbuild = [
  "bundle exec rake assets:precompile",
]

[[env]]
name = "RAILS_ENV"
value = "production"

[[env]]
name = "WEB_CONCURRENCY"
value = "auto"

[[env]]
name = "RAILS_MAX_THREADS"
value = "3"

[[env]]
name = "SECRET_KEY_BASE"
generator = "random-secret"

[services]
web = "rails s -b 0.0.0.0 -p $PORT"
